---
title: "Building Summary"
author: "Maggie Douglas"
date: "2026-02-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Conversion factors

```{r conv}
dollars_kwh <- 0.0813
co2_kg_kwh <- 0.299511787
```

## Load libraries + data

```{r load}
library(tidyverse)
library(DT)

kwh <- read.csv("./data/kwh_by_building.csv", strip.white = TRUE)
key <- read.csv("./data/building_list_FY25.csv", strip.white = TRUE)
kwh_daily <- read.csv("./data/FY25 PPL Electricity Data.csv", strip.white = TRUE)
```

## Check

```{r check}
str(kwh)
str(key)
str(kwh_daily)
```

## Join datasets

```{r join}
comb <- kwh %>%
  left_join(key, by = "NAME", relationship = "many-to-one")

# generate key for building info
comb_key <- comb %>%
  select(type, NAME, main_meter, date_constr, date_acqd, date_reno, sqft) %>%
  unique()

# generate key to connect meters to building names
meter_key <- comb %>%
  select(meter_origin, NAME)
```

## Subset

```{r filter}
res_hall_S <- filter(comb, type == "Res Hall - S")
```

## Aggregate

```{r agg}
agg <- res_hall_S %>%
  group_by(NAME, type) %>%
  summarize(kwh_tot = sum(kwh_tot, na.rm = TRUE),
            sqft = mean(sqft, na.rm = TRUE))
```

## Transform

```{r transform}
# different choices for rounding are okay, but need to implement round() successfully
trans <- agg %>%
  mutate(kwh_sqft = round(kwh_tot/sqft,digits = 2),
         dollars = round(kwh_tot*dollars_kwh, digits = 0),
         ghg_kgCO2 = round(kwh_tot*co2_kg_kwh, digits = 0)) %>%
  arrange(-kwh_tot) %>%
  select(-type)
```

## Tables

```{r table_electric}
datatable(trans,
          filter = 'top',
          rownames = FALSE)
```

```{r table_buildings}
buildings <- filter(key, type == "Res Hall - S") %>%
  arrange(main_meter, -sqft) %>%
  select(NAME, sqft, main_meter)

datatable(buildings,
          filter = 'top',
          rownames = FALSE)
```

## Master data 

```{r master}
agg_tot <- comb %>%
  group_by(NAME, type) %>%
  summarize(kwh_tot = sum(kwh_tot, na.rm = TRUE),
            sqft = mean(sqft, na.rm = TRUE))

trans_tot <- agg_tot %>%
  mutate(kwh_sqft = round(kwh_tot/sqft,digits = 2),
         dollars = round(kwh_tot*dollars_kwh, digits = 0),
         ghg_kgCO2 = round(kwh_tot*co2_kg_kwh, digits = 0)) %>%
  arrange(type, -kwh_tot) 
```

## Format daily kwh data for downstream analysis

```{r daily}
# Generate daily kwh data at the building level + join to building info
comb_daily <- kwh_daily %>%
  left_join(meter_key, by = "meter_origin", relationship = "many-to-one") %>%
  group_by(NAME, date) %>%
  summarize(kwh = sum(total_kwh, na.rm = TRUE),
           ave_temp = mean(ave_temp, na.rm = TRUE)) %>%
  filter(NAME != "") %>%
  left_join(comb_key, by = "NAME") %>%
  mutate(kwh_sqft = kwh/sqft,
         dollars = kwh*dollars_kwh,
         co2_kg = kwh*co2_kg_kwh,
         date = mdy(date),
         month = month(date, label = TRUE),
         day = wday(date, label = TRUE))

main_meter <- filter(kwh_daily, meter_origin == "W High St (37 Big Buildings)") %>%
  mutate(date = mdy(date),
         month = month(date, label = TRUE),
         day = wday(date, label = TRUE),
         dollars = total_kwh*dollars_kwh,
         co2_kg = total_kwh*co2_kg_kwh,)
```

## Graph data

```{r stacked_bar, warning = F}
ggplot(comb_daily, aes(x = month, y = kwh, fill = type)) +
  geom_col(stat = "identity") +
  theme_bw() +
  labs(x = "")
```

```{r density, warning = F}
ggplot(main_meter, aes(x = total_kwh, fill = day)) +
  geom_density(alpha = 0.5) +
  theme_bw() +
  labs(x = "")
```

```{r boxplot, warning = F}
ggplot(main_meter, aes(x = day, y = total_kwh, fill = day)) +
  geom_boxplot() +
  theme_bw() +
  labs(x = "")
```

```{r scatter}
ggplot(main_meter, aes(x = ave_temp, y = total_kwh, col = month)) +
  geom_point() +
  theme_bw() +
  labs(x = "Daily Avereage Temperature (F)", y = "Electricity use (kWh)", 
       title = "Main Meter electricity use by outdoor temperature")
```

```{r line}
ggplot(main_meter, aes(x = date, y = total_kwh)) +
  theme_bw() +
  labs(x = "", y = "Electricity use (kWh)") +
  annotate("rect", xmin = mdy("09/02/24"), xmax = mdy("12/21/24"), 
                ymin = -Inf, ymax = Inf,
            fill = "lightblue", alpha = 0.5) +
    annotate("rect", xmin = mdy("01/20/25"), xmax = mdy("05/13/25"), 
                ymin = -Inf, ymax = Inf,
            fill = "lightblue", alpha = 0.5) +
  geom_line() 
```
