---
title: "Executive Summary"
output:
  workflowr::wflow_html:
    toc: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Here we share a high-level summary and set of recommendations arising from our analyses taken as a whole. These take-home messages were generated collaboratively by the class. 

### Fiscal Year 2025 electricity usage, cost, and carbon footprint

In FY25 Dickinson managed ~1.9 million square feet of building space. This was associated with:

+ 17.2 million kWh of electricity usage
+ A cost of more than $1.4 million 
+ Emissions equivalent to ~5185 MT CO~2~

The college also realized significant savings from the solar array:

+ Created 4.3 kWh of electricity
+ Saved $347,863
+ Prevented emissions equivalent to ~1,286 MT CO~2~

Electricity use in many campus buildings showed a strong seasonal pattern, consistent with the role of electricity in heating, cooling, and ventilation (HVAC). Across Dickinson as a whole, cooling is a larger driver of electricity usage than heating, because heating in most buildings relies on natural gas. This helps to explain why campus electricity use peaked in summer, even though that is a time of low student occupancy. 

### Assessment of Dickinson's electricity performance (FY25)

Benchmarking against other U.S. College and University buildings as reported by the EIA (2022) shows that:

  + Buildings on the Main Meter and Weis Meter accounted for 74% of campus electricity usage. On average they used 10.4 and 11.4 kWh/sqft of building space, extremely close to the median for similar U.S. buildings (10.3 kWh/sqft, typical range: 7.4-14.3 kWh/sqft).
  + Most individually metered buildings at Dickinson were significantly below the typical range of values for similar U.S. buildings. Their low values are likely due in part to electricity usage associated with cooling that occurs off-site at the Central Energy Plant (which is not measured in their individual meters). 
  + Overall, average electricity usage across campus in FY25 was 9.1 kWh/sqft, slightly below the median value for similar U.S. buildings. This suggests that Dickinson is doing well overall, but still has potential to reduce usage further. 

### Strategies for electricity use reduction

#### (1) Consolidate summer housing into fewer, more efficient buildings

Due to cooling demand, summer is a time of high electricity usage but low residential occupancy. Moving students into fewer, more energy-efficient buildings would allow the remaining buildings to be maintained at a higher temperature and reduce electricity usage. This would also help the college meet its agreements with our energy supplier. Buildings can be ranked by their electricity efficiency using the interactive tables here: Small Residence Halls, Medium Residence Halls, Large Residence Halls. This strategy is especially important because Cumberland County is likely to become 2-11^o^F warmer by late century under climate change (Leary 2025). Projecting from our FY25 results, a 5^o^F increase in summer temperatures would require an additional 3800 kWh per day ($300/day at current rates) for the Main Meter alone.

#### (3) Invest in centralized climate control + building automation systems 

Because the Central Energy Plant helps to heat and cool the majority of building space on campus, improvements there will have widespread effects. 

+ Greenhouse Gas Inventory recommendations
+ Inefficiency of window units and other ad hoc systems 

Several of our building case studies suggested the value of existing building automation systems (BAS) to reduce electricity usage (for example, see XXX). These systems automate the regulation of heating, cooling, air flow, and lighting in response to occupancy and other factors. The College could consider expanding the use of such systems to reap the benefits in additional spaces. 

#### (4) Prioritize and assess energy efficiency in new builds and renovations

New buildings and renovations provide an opportunity to advance (or set back) energy savings. We recommend the College bring in appropriate staff from Facilities Management to consult on such projects early in the design process. 

Furthermore, we recommend using electricity data to assess the effect of renovations on building performance. For example, our analysis could be expanded to include electricity use in Drayer Hall prior to its 2023 renovation, enabling a direct comparison of pre- and post-renovation energy consumption (see [Drayer Hall case study](Report_II_Residential-L.html)). The relatively new [Durden Athletic Complex](Report_II_Other.html) could also provide an interesting pre- and post- comparison since FY25 coincided with a period of construction in that complex. 

#### (5) Improve insulation + green infrastructure

See Althouse Hall results

Cite paper from 

#### (2) Engage students and staff in electricity savings

An electricity orientation could help students learn about electricity-intensive activities (e.g. laundry, using the elevator), and encourage them to reduce unnecessary consumption in support of Dickinson's sustainability goals. It could also provide site-specific information in residences with special heating and cooling systems (e.g. [Treehouse](Report_II_Med-Residential-Building.Rmd)).

### Priorities for future data collection


### Sources

Leary, N. (2025). Climate Risks and Resilience in Cumberland County: Synthesis Report. Center for Sustainability Education. Dickinson College. https://www.dickinson.edu/download/downloads/id/16410/climate_risks_and_resilience_in_cumberland_county_synthesis_report.pdf
